repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1 # select the tag or revision you want, or run `pre-commit autoupdate`
    hooks:
      - id: autopep8
